### ISSUE TITLE
Some issues when migrating vqe_h2o.ipynb to use CO2

### ISSUE THREAD

**Issue by buttercutter** [tencent-quantum-lab/tensorcircuit#120]
I am trying to migrate [vqe_h2o.ipynb](https://github.com/tencent-quantum-lab/tensorcircuit/blob/master/docs/source/tutorials/vqe_h2o.ipynb) to use `CO2` [carbon dioxide molecule](https://gist.github.com/buttercutter/19cd09def3360f88db509670179fd54c/f48198df7129dcce72979f2d17c84efe82f450f4#file-vqe_co2-ipynb).

1. For `print(fh.terms[((0, 1), (0, 0))])` which is the two-body coefficients, it gives `-36.01932840424451`.  When I try to access the one-body coefficients using the following code snippet, nothing is printed out.  Could you advise how to decide which [orbitals to be removed](https://youtu.be/3B04KB0pDwE?t=947) for `CO2` ?  The video comes with [a notebook code](https://github.com/qiskit-community/intro-to-quantum-computing-and-quantum-hardware/blob/master/labs/introqcqh-lab-8.zip) which no longer runs since it is using deprecated `qiskit-chemistry` package.  Besides, when I checked https://qiskit.org/documentation/nature/tutorials/05_problem_transformers.html#The-ActiveSpaceTransformer , code box `[11]` still need to be manually hand-picking the active orbitals.  Correct me if I miss anything though

```python
one_body_terms = fh.terms
for term, coefficient in one_body_terms.items():
    if len(term) == 2:
        # Only consider terms with one creation and one annihilation operator
        i, j = term
        if i[0] == "c" and j[0] == "c":
            print("Term: c^\dagger_{} c_{} Coefficient: {}".format(i[1], j[1], coefficient))
```

2. Besides, the kernel crashes when running `ma = tc.quantum.PauliStringSum2COO_numpy(lsa, wa)`

![image](https://user-images.githubusercontent.com/3324659/216773409-7a4761e4-89a5-47f0-8010-fae128d84509.png)

![image](https://user-images.githubusercontent.com/3324659/216770338-bb3d263a-b7e1-43f7-95c0-5bb56671ea14.png)

**Comment by buttercutter** [comment]
@liwt31 Why did you remove the line `if i[0] == "c" and j[0] == "c":`  ?

**Comment by liwt31** [comment]
> @liwt31 Why did you remove the line `if i[0] == "c" and j[0] == "c":` ?

i, j are tuples of integers. No string is contained.

**Comment by buttercutter** [comment]
@liwt31 I suppose that I cannot use `one_body_terms = fh.terms` to do point group symmetry ?

Do I need to resort to using [Q-Chem](https://manual.q-chem.com/5.4/sec_symm.html) or [ORCA](https://sites.google.com/site/orcainputlibrary/geometry-input) ?

I noticed that there is [an external user library that does point group symmetry](https://github.com/mcodev31/libmsym), but I am not familiar with it.

**Comment by liwt31** [comment]
> @liwt31 I suppose that I cannot use `one_body_terms = fh.terms` to do point group symmetry for determining orbital removal index ?

No, I believe more advanced tools are necessary.

> Do I need to resort to using [Q-Chem](https://manual.q-chem.com/5.4/sec_symm.html) or [ORCA](https://sites.google.com/site/orcainputlibrary/geometry-input) ?
> 
> I noticed that there is [an external user library that does point group symmetry](https://github.com/mcodev31/libmsym), but I am not familiar with it.

To the best of my knowledge currently there's no readily available tool for this, unfortunately. And I don't believe `tensorcircuit` is the correct place to implement it.
IMHO the only viable way is to read the paper I mentioned above along with several important references in the paper, understand the theory, and then implement the reduction by yourself.

**Comment by buttercutter** [comment]
@liwt31 @gigaBrainIO

Some qiskit people told me to check the paper reference found in https://qiskit.org/documentation/nature/stubs/qiskit_nature.second_q.transformers.ActiveSpaceTransformer.html

What do you think ?

**Comment by liwt31** [comment]
This is certainly a viable method.  If you do not care so much about accuracy, you can directly remove orbitals with the highest and lowest energy and retain the ones that are closest to HOMO/LUMO orbitals

**Comment by buttercutter** [comment]
The [relevant code snippet within ActiveSpaceTransformer](https://github.com/Qiskit/qiskit-nature/blob/8a38b779b3920c6a506d75591e91bcc68733e0a6/qiskit_nature/transformers/second_quantization/electronic/active_space_transformer.py#L298) is as follows, however I am not sure how it works.

```python
    def _determine_active_space(
        self, grouped_property: GroupedElectronicProperty
    ) -> Tuple[List[int], List[int]]:
        """Determines the active and inactive orbital indices.
        Args:
            grouped_property: the `GroupedElectronicProperty` to be transformed.
        Returns:
            The list of active and inactive orbital indices.
        """
        particle_number = grouped_property.get_property(ParticleNumber)
        if isinstance(self._num_electrons, tuple):
            num_alpha, num_beta = self._num_electrons
        elif isinstance(self._num_electrons, (int, np.integer)):
            num_alpha = num_beta = self._num_electrons // 2

        # compute number of inactive electrons
        nelec_total = particle_number._num_alpha + particle_number._num_beta
        nelec_inactive = nelec_total - num_alpha - num_beta

        self._validate_num_electrons(nelec_inactive)
        self._validate_num_orbitals(nelec_inactive, particle_number)

        # determine active and inactive orbital indices
        if self._active_orbitals is None:
            norbs_inactive = nelec_inactive // 2
            inactive_orbs_idxs = list(range(norbs_inactive))
            active_orbs_idxs = list(
                range(norbs_inactive, norbs_inactive + self._num_molecular_orbitals)
            )
        else:
            active_orbs_idxs = self._active_orbitals
            inactive_orbs_idxs = [
                o
                for o in range(nelec_total // 2)
                if o not in self._active_orbitals and self._mo_occ_total[o] > 0
            ]

        return (active_orbs_idxs, inactive_orbs_idxs)
```

**Comment by buttercutter** [comment]
> directly remove orbitals with the highest and lowest energy and retain the ones that are closest to HOMO/LUMO orbitals

You mean [Gouterman orbitals](https://www.youtube.com/watch?v=HTVNBHTjG-I) ?

PS:  I need some theoretical study on  LUMO and LUMO+1 Gouterman orbitals, as well as HOMO-LUMO gaps

**Comment by buttercutter** [comment]
@liwt31 Thanks for your suggestion, I have the LUMO and HOMO molecular orbitals now for `Fe2+` metallic ion for carbon capture MOFs. 

![molecular_orbitals_Fe2_CO2](https://user-images.githubusercontent.com/3324659/223397002-75d4e5a3-8cbd-41ab-b5ae-adc84d0d7ebc.png)
