### ISSUE TITLE
Change the definition of p for generaldepolarizingchannel

### ISSUE THREAD

**Issue by liwt31** [tencent-quantum-lab/tensorcircuit#129]
## Issue Description
If `p` is a list then the definition is fine. However, if `p` is a float, the channel is defined as

$$
\mathcal{E}(\rho) = (1 - 3p)\rho + p(X\rho X + Y\rho Y + Z\rho Z)
$$

which is counter-intuitive and not compatible with (all?) existing packages and papers.

## Proposed Solution

Change the definition to

$$
\mathcal{E}(\rho) = (1 - p)\rho + p/3(X\rho X + Y\rho Y + Z\rho Z)
$$

This is going to be a backward-incompatible change that may silently change the semantics of existing code.

## Additional References

Circ [https://quantumai.google/reference/python/cirq/DepolarizingChannel](https://quantumai.google/reference/python/cirq/DepolarizingChannel)
Qiskit [https://qiskit.org/documentation/stubs/qiskit_aer.noise.depolarizing_error.html](https://qiskit.org/documentation/stubs/qiskit_aer.noise.depolarizing_error.html)
Pennylane [https://docs.pennylane.ai/en/stable/code/api/pennylane.DepolarizingChannel.html](https://docs.pennylane.ai/en/stable/code/api/pennylane.DepolarizingChannel.html)

For papers see 8.103 of Nielsen&Chuang, Eq. 24 of https://arxiv.org/pdf/2112.15540.pdf, Eq.2.6 of https://arxiv.org/pdf/2004.02388.pdf, Eq.3 of https://arxiv.org/pdf/2003.04941.pdf and many more

**Comment by refraction-ray** [comment]
The semantic in TC is: if a float ``a`` is in the place that should be a list, then ``[a, a, a, a ...]`` input is implicitly assumed. According to this, the current convention is consistent with TC design.

A mitigation is add a warning tag in the docstring for the method, explicitly telling the users that the convention for this noise channel is different from others. I have no strong preference compared the two approaches: "keep and warning in doc" or "change to consistent with other conventions". Just slightly prefer keeping the definition unless there is another strong reason against that. eg. when translating noise model (currently we have no such translation anyway), a consistent interface would help (but the real situation would be that many noise channel definition are not consistent across different packages, I guess?)

**Comment by liwt31** [comment]
Another solution: apart from the `generaldepolarizingchannel`, implement a new function named `simpledepolarizingchannel` which only accepts one argument $p$ and has a similar interface with other packages. Then the float-type argument in `generaldepolarizingchannel` can be kept or removed.

**Comment by refraction-ray** [comment]
> Another solution: apart from the `generaldepolarizingchannel`, implement a new function named `simpledepolarizingchannel` which only accepts one argument p and has a similar interface with other packages. Then the float-type argument in `generaldepolarizingchannel` can be kept or removed.

yes, but I am afraid whether this adding will further complicate the depolarizing like channel method in TC already

**Comment by liwt31** [comment]
> > Another solution: apart from the `generaldepolarizingchannel`, implement a new function named `simpledepolarizingchannel` which only accepts one argument p and has a similar interface with other packages. Then the float-type argument in `generaldepolarizingchannel` can be kept or removed.
> 
> yes, but I am afraid whether this adding will further complicate the depolarizing like channel method in TC already

Indeed. Ideally, the interfaces should be
```
def depolarizingchannel(p: float, n_qubit): ... # The same interface with all other packages
def generaldepolarizingchannel(p: list, n_qubit): ... # The general interface
```
If such refactoring is done, deprecation warnings can be added appropriately for a relatively smooth conversion.
