### ISSUE TITLE
Enhance <QAOA portfolio tutorial>

### ISSUE THREAD

**Issue by FelixXu35** [tencent-quantum-lab/tensorcircuit#150]
## Task description

Separate the current tutorial into two files.
Increase the accessibility to both beginners and experienced developers.

## Implementation

1. Solving QUBO problem using QAOA
    - Overview
    - QUBO problem: an introduction
    - An example: 2-qubit QUBO, previously on the tutorial
    - Code
        - General Definition
        - Function definition: directly define the general (nqubits>2) ones
            - Ansatz
            - Cost function
            - Solve
        - Results visualization: show all results in a list, sorted with probabilities
    - General case with code
2. Portfolio optimization using QAOA
    - Overview
    - HM model: what is portfolio optimization, relation to QUBO
    - Artificial data: generated by `qiskit_finance`
        - different mixer
        - different cost function
        - classical solver
    - real data: benchmarking paper
        - compare the performance

## Requirements

difficulty: not much

**Comment by refraction-ray** [comment]
for the real financial data, you can use this package as data fetcher if you like: https://github.com/refraction-ray/xalpha. My concern is: the two notebooks, and the first one with qaoa tutorials will have too much overlap and replicated code (ie. the users may read several tutorials with very similar topics and implementations), what is the motivation behind such a tutorial splitting?

**Comment by FelixXu35** [comment]
I personally think the portfolio is a more popular keyword (searched more than QUBO) and it is now buried in the QUBO part. In the list of tutorials, there is no "portfolio". Even if someone knows that the portfolio optimization is in this [page](https://tensorcircuit.readthedocs.io/en/latest/tutorials/qaoa_portfolio_optimization.html) it is still difficult to find the correct part. 

I agree there might be too much QAOA if I follow this proposal. Maybe I could set the name as "solving portfolio optimization with QAOA" and then only introduce the general case of QUBO and portfolio optimization.

**Comment by refraction-ray** [comment]
Agreed. Just change the title is better: Solving portfolio optimization as QUBO problem with QAOA

**Comment by FelixXu35** [comment]
Finished
