### ISSUE TITLE
Backend agnostic implementation of quantum Hamiltonian generation

### ISSUE THREAD

**Issue by refraction-ray** [tencent-quantum-lab/tensorcircuit#161]
## Task description

Revise the following code using tensorcircuit backend API instead of tf API, making it backend agnostic

## Implementation

Revise the following code using tensorcircuit backend API instead of tf API, making it backend agnostic, at least work for both tensorflow and jax (the efficiency could also be benchmarked)

https://github.com/tencent-quantum-lab/tensorcircuit/blob/master/tensorcircuit/quantum.py#L1167-L1468

You can add the missing backend method in `/tensorcircuit/backends` like the bitwise shift operations if necessary

## Requirements

Difficulty: ★★

**Comment by refraction-ray** [comment]
@king-p3nguin finished this issue

**Comment by king-p3nguin** [comment]
I see. I would like to be assigned to this issue.
