### ISSUE TITLE
Support trainable adptive circuit

### ISSUE THREAD

**Issue by Marsmmz** [tencent-quantum-lab/tensorcircuit#179]
## Issue Description

 It will be really healpful if tensorcircuit can support quantum circuits supporting measurement in the middle of a quantum simulation, which the type of following gates can depend on the classical results of these measurements. More ideally, intruducing gradient optimization method to this type of circuits can be really helpful.

## Proposed Solution

 Perhaps giving conditing to the circuit design (like 'if') will be a promising way to do this. 

thanks!

**Comment by refraction-ray** [comment]
> It will be really healpful if tensorcircuit can support quantum circuits supporting measurement in the middle of a quantum simulation, which the type of following gates can depend on the classical results of these measurements. 

I think this can be done, see https://github.com/tencent-quantum-lab/tensorcircuit/issues/52.

> intruducing gradient optimization method to this type of circuits can be really helpful

I think grad and jit also compatible with two paradigms present in the above issue line

**Comment by Marsmmz** [comment]
Thanks! I'll go and check it out
