### ISSUE TITLE
Implementation of SHVQE with QAS

### ISSUE THREAD

**Issue by royess** [tencent-quantum-lab/tensorcircuit#190]
## Issue Description

Implement Schrodinger-Heisenberg quantum variational eigensolver (SHVQE) with quantum architecture search.

## Proposed Solution

I have already implemented it as a script (using tensorcircuit) at <https://github.com/royess/QC-Contest-underwater/blob/main/shvqe_clifford.py> and want to see whether I can contribute it to the tensorcircuit package in some ways.

## Additional References

The paper: <https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.131.060406>

**Comment by refraction-ray** [comment]
thanks for this nice proposal. you can contribute this script also under /examples (in .py format). The script is better self-contained (can be directly called and no IO is required, or at most one input file is ok and we can comment all code lines for file output)
