### ISSUE TITLE
tensor network representation of a tensor circuit

### ISSUE THREAD

**Issue by Marsmmz** [tencent-quantum-lab/tensorcircuit#196]
I'm working with tensorcircuit to build my quantum circuit and I've notice than we can use **projector** from `tensorcircuit.quantum` and it will return a `QuOperator` object which represent an operator in tensor network form. However, I can't figure out how to apply this porjector to my circuit. I think perhaps I need to represent my circuit in tensor network form. But I can't find relevent functions. 

Can anybody please tell me how I can represent my `tc.Circuit` class circuit to as a **tensor network**? Many thanks!

**Comment by refraction-ray** [comment]
say if you have ``c = tc.Circuit(n)``,  then ``c.quvector()`` is enough to extract the circuit as a tensor network in the format of `QuVector`

**Comment by Marsmmz** [comment]
Thanks a lot!
