### ISSUE TITLE
jit compile circuit with any gate

### ISSUE THREAD

**Issue by Marsmmz** [tencent-quantum-lab/tensorcircuit#200]
I'm using tensorflow as backend and trying to jit compile a circuit with any_gates where thire unitaries are parameters of the jit function. However, any_gate needs unitary with dtype complex128 but during jit compile process, only SymbolicTensor is pass to the unitary, causing error. Are there any way to go around this?

<img width="887" alt="image" src="https://github.com/tencent-quantum-lab/tensorcircuit/assets/100653463/9f15fb7a-e9ec-4580-a860-6b2c346ab6a9">

**Comment by refraction-ray** [comment]
please attached the minimal code demo to reproduce the error

**Comment by refraction-ray** [comment]
closed as stale, feel free to open again if there is reproducible demo
