### ISSUE TITLE
Stabilizer simulation example utilizing stim backend

### ISSUE THREAD

**Issue by refraction-ray** [tencent-quantum-lab/tensorcircuit#211]
## Task description

Add an example python script `stabilizer_stim_sim.py` in `/examples` which showcases stabilizer circuit simulation using tc interface with stim backend.

## Implementation

The script includes:
1. Clifford circuit with mid-circuit measurement defined in tc
2. Transform the circuit object into Stim circuit object with the helper function defined in the same script (input: tc circuit, output: stim circuit)(can utilize `c._qir` and `c._extra_qir`, using `c.measure_instruction` to get the mid circuit measurement recorded in extra_qir and using `c.mid_measurement` for the real functionality)
3. Simulate the circuit in stim and extract the stabilizer tableau 
4. Compute the entanglement entropy of the output state with the helper function defined in the same script (input: stabilizer tableau representation, output: entanglement entropy value) (see Ref 3, it would be better to try hard to accelerate this function)
5. Validate the correctness by directly computing entanglement from tc (mid-circuit measurement results might require to be averaged)

## References:

1. https://github.com/tencent-quantum-lab/tensorcircuit/issues/159
2. https://github.com/quantumlib/Stim
3. https://quantumcomputing.stackexchange.com/questions/16718/measuring-entanglement-entropy-using-a-stabilizer-circuit-simulator
4. https://arxiv.org/abs/quant-ph/0406196

**Comment by refraction-ray** [comment]
@anonymousr007 , great, feel free to open a PR for this issue. Should you encounter any further questions or need assistance while working on it, please don't hesitate to reach out. We're here to help and look forward to your contributions.

**Comment by refraction-ray** [comment]
> is their a way to plot in stim

https://quantumcomputing.stackexchange.com/questions/25734/how-can-i-visualize-a-stim-circuit

**Comment by refraction-ray** [comment]
@AbdullahKazi500 ， you can open an PR so that I can review the script if you have already got the example work and the result entanglement is checked to be correct

**Comment by king-p3nguin** [comment]
Hi, I would also like to work on this issue.
