### ISSUE TITLE
tensorflow backend with torch interface has bugs in tensorcircuit==0.2.1

### ISSUE THREAD

**Issue by XiaoTailong** [tencent-quantum-lab/tensorcircuit#24]
import torch
import tensorcircuit as tc
tc.set_backend("tensorflow")
def f(params):
    c = tc.Circuit(1)
    c.rx(0, theta=params[0])
    c.ry(0, theta=params[1])
    return c.expectation([tc.gates.z(), [0]])
f_torch = tc.interfaces.torch_interface(f, jit=True)
a = torch.ones([2], requires_grad=True)
b = f_torch(a)
c = b ** 2
c.backward()
print(a.grad)

Erros
===========================
RuntimeError                              Traceback (most recent call last)
<ipython-input-6-7687aa241920> in <module>
      9 f_torch = tc.interfaces.torch_interface(f, jit=True)
     10 a = torch.ones([2], requires_grad=True)
---> 11 b = f_torch(a)
     12 c = b ** 2
     13 c.backward()

~/.conda/envs/RLQM_torch/lib/python3.6/site-packages/tensorcircuit/interfaces.py in forward(ctx, *x)
    126         def forward(ctx: Any, *x: Any) -> Any:  # type: ignore
    127             ctx.xdtype = [xi.dtype for xi in x]
--> 128             x = general_args_to_numpy(x)
    129             x = numpy_args_to_backend(x)
    130             y = fun(*x)

~/.conda/envs/RLQM_torch/lib/python3.6/site-packages/tensorcircuit/interfaces.py in general_args_to_numpy(args, same_pytree)
     30         alone = True
     31     for i in args:
---> 32         res.append(tensor_to_numpy(i))
     33     if not same_pytree:
     34         return res  # all list

~/.conda/envs/RLQM_torch/lib/python3.6/site-packages/tensorcircuit/interfaces.py in tensor_to_numpy(t)
     18 def tensor_to_numpy(t: Tensor) -> Array:
...
---> 20         return t.numpy()
     21     except AttributeError:
     22         return np.array(t)

RuntimeError: Can't call numpy() on Variable that requires grad. Use var.detach().numpy() instead.

Torch interface error. The forward function in torch model cannot work well in gradient tensor.

**Comment by refraction-ray** [comment]
Thanks for you issue report. First of all, the code you provided works well in my local test, and I want to divide this issue into several aspects.

1. I am currently refactoring the code of interface part, you can update tensorcircuit via GitHub (or wait for next pip release) to see whether the code works fine. Though v0.2.1 should run the code, I am not sure the cause of the error.

2. That being said, pytorch backend ``numpy`` method indeed fails when the input tensor requires grad and in gradient track mode. Therefore, I will fix this method. However, since the interface utilize autograd function pipeline, the ``numpy()`` method should works fine even with tensor requires grad, just as the case you show.

In sum, I fix a bug on pytorch backend ``numpy()`` method thanks to your issue. However, I don't think this issue is relevant to your exact use case since the code should be fine.

My suggestion for you to make the code work: 1 try to run with GitHub mater version of tensorcircuit or wait for next version pip release 2 and you may still fail since I actually don't identify the cause of the bug for now (I see not bug on my side), in that case, pls provide more information about you enviroment.

**Comment by XiaoTailong** [comment]
May pip install cannot work well. The local source installation from Github may work well. I'll try it.

**Comment by refraction-ray** [comment]
If it still fails, pls provide me at least the version of torch, maybe different versions of torch take the autograd function pipeline differently

**Comment by XiaoTailong** [comment]
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
absl-py                   0.15.0                   pypi_0    pypi
astunparse                1.6.3                    pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
ca-certificates           2022.6.15            ha878542_0    conda-forge
cached-property           1.5.2                    pypi_0    pypi
cachetools                4.2.4                    pypi_0    pypi
certifi                   2021.5.30        py36h5fab9bb_0    conda-forge
charset-normalizer        2.0.12                   pypi_0    pypi
clang                     5.0                      pypi_0    pypi
cpuonly                   1.0                           0    pytorch
cudatoolkit               11.3.1               h2bc3f7f_2    defaults
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cython                    0.29.24          py36hc4f0c31_0    conda-forge
dataclasses               0.8                      pypi_0    pypi
dbus                      1.13.6               h5008d03_3    conda-forge
decorator                 4.4.2                    pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
expat                     2.4.8                h27087fc_0    conda-forge
flatbuffers               1.12                     pypi_0    pypi
fontconfig                2.14.0               h8e229c2_0    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
gast                      0.4.0                    pypi_0    pypi
gettext                   0.19.8.1          h73d1719_1008    conda-forge
glib                      2.70.2               h780b84a_4    conda-forge
glib-tools                2.70.2               h780b84a_4    conda-forge
google-auth               1.35.0                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.47.0                   pypi_0    pypi
gst-plugins-base          1.14.0               hbbd80ab_1    defaults
gstreamer                 1.14.0               h28cd5cc_2    defaults
h5py                      3.1.0                    pypi_0    pypi
icu                       58.2              hf484d3e_1000    conda-forge
idna                      3.3                      pypi_0    pypi
importlib-metadata        4.8.3                    pypi_0    pypi
intel-openmp              2022.0.1          h06a4308_3633    defaults
ipykernel                 5.5.6                    pypi_0    pypi
ipython                   7.16.3                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
jedi                      0.17.2                   pypi_0    pypi
jpeg                      9e                   h166bdaf_1    conda-forge
jupyter-client            7.1.2                    pypi_0    pypi
jupyter-core              4.9.2                    pypi_0    pypi
keras                     2.6.0                    pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.3.1            py36h605e78d_1    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lerc                      3.0                  h9c3ff4c_0    conda-forge
libblas                   3.9.0                8_openblas    conda-forge
libcblas                  3.9.0                8_openblas    conda-forge
libdeflate                1.10                 h7f98852_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgfortran-ng            7.5.0               h14aa051_20    conda-forge
libgfortran4              7.5.0               h14aa051_20    conda-forge
libglib                   2.70.2               h174f98d_4    conda-forge
libgomp                   12.1.0              h8d9b700_16    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0                8_openblas    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.12          pthreads_hb3c22a3_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libstdcxx-ng              12.1.0              ha89aaad_16    conda-forge
libtiff                   4.3.0                h0fcbabc_4    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp-base              1.2.2                h7f98852_1    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxml2                   2.9.9                h13577e0_2    conda-forge
libzlib                   1.2.12               h166bdaf_1    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
markdown                  3.3.7                    pypi_0    pypi
matplotlib                3.1.0                    py36_0    conda-forge
matplotlib-base           3.1.0            py36h5f35d83_0    conda-forge
mkl                       2022.0.1           h06a4308_117    defaults
ncurses                   6.3                  h27087fc_1    conda-forge
nest-asyncio              1.5.5                    pypi_0    pypi
networkx                  2.5.1                    pypi_0    pypi
ninja                     1.11.0               h924138e_0    conda-forge
numpy                     1.19.5                   pypi_0    pypi
oauthlib                  3.2.0                    pypi_0    pypi
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openssl                   1.1.1p               h166bdaf_0    conda-forge
opt-einsum                3.3.0                    pypi_0    pypi
parso                     0.7.1                    pypi_0    pypi
pcre                      8.45                 h9c3ff4c_0    conda-forge
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    7.2.0            py36h8328e55_2    conda-forge
pip                       21.2.4             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.30                   pypi_0    pypi
protobuf                  3.19.4                   pypi_0    pypi
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0                    pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pygments                  2.12.0                   pypi_0    pypi
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyqt                      5.9.2            py36hcca6a23_4    conda-forge
python                    3.6.15          hb7a2778_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-graphviz           0.19.1                   pypi_0    pypi
python_abi                3.6                     2_cp36m    conda-forge
pytorch                   1.4.0               py3.6_cpu_0  [cpuonly]  pytorch
pyzmq                     23.2.0                   pypi_0    pypi
qt                        5.9.7                h5867ecd_1    defaults
qutip                     4.2.0               np111py36_2    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
requests                  2.27.1                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rsa                       4.8                      pypi_0    pypi
scipy                     1.2.1            py36h09a28d5_1    conda-forge
setuptools                49.6.0           py36h5fab9bb_3    conda-forge
sip                       4.19.8          py36hf484d3e_1000    conda-forge
six                       1.15.0                   pypi_0    pypi
sqlite                    3.39.0               h4ff8645_0    conda-forge
tensorboard               2.6.0                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
tensorcircuit             0.2.1                    pypi_0    pypi
tensorflow                2.6.2                    pypi_0    pypi
tensorflow-estimator      2.6.0                    pypi_0    pypi
tensornetwork             0.4.5                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
tk                        8.6.12               h27826a3_0    conda-forge
torchaudio                0.4.0                      py36    pytorch
torchvision               0.5.0                  py36_cpu  [cpuonly]  pytorch
tornado                   6.1              py36h8f6f2f9_1    conda-forge
traitlets                 4.3.3                    pypi_0    pypi
typing                    3.10.0.0           pyhd8ed1ab_0    conda-forge
typing-extensions         3.7.4.3                  pypi_0    pypi
urllib3                   1.26.9                   pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
werkzeug                  2.0.3                    pypi_0    pypi
wheel                     0.37.1                   pypi_0    pypi
wrapt                     1.12.1                   pypi_0    pypi
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zipp                      3.6.0                    pypi_0    pypi
zlib                      1.2.12               h166bdaf_1    conda-forge
zstd                      1.5.2                h8a70e8d_1    conda-forge
==========================================
It still fails.

**Comment by XiaoTailong** [comment]
toch version is 1.4.0  .

**Comment by refraction-ray** [comment]
> toch version is 1.4.0 and it still fails.

It is too old, what about upgrading torch?

**Comment by XiaoTailong** [comment]
> > toch version is 1.4.0 and it still fails.
> 
> It is too old, what about upgrading torch?

Yes torch is too old. I upgrage to 1.10 and it works well. Thanks. I suggest that when installing tensorcircuit, the version of the required packages can be verified. I may be helpful.

**Comment by refraction-ray** [comment]
Thanks for you careful test, glad that it finally works :)

In terms of the suggestion on version requirements, actually tensorcircuit has a very flexible setup dependency system. Indeed, pytorch itself is not a necessary dependence for tensorcircuit, let alone its version.

Such design are two-fold.
On the one hand, the software is much easier to install and has very small probability that is conflict with existing python enviroments.
On the other hand, the freedom for user is very lager. The users should upgrade their dependencies or install new packages from time to time, if needed.
