### ISSUE TITLE
Add and complete the "depolarizing channel" part in  tensorcircuit/channels.py

### ISSUE THREAD

**Issue by yutuer21** [tencent-quantum-lab/tensorcircuit#27]
# TEP - Title

Author
yuqinchen

Status
Draft

Created
2022-7-4

## Abstract

Add and complete the "depolarizing channel" part in  tensorcircuit/channels.py

## Motivation and Scope

It is an important part of noisemodel to add to quantum circuit for noise simulation and error mitigation.
It is my startpoint to contribute to TensorCircuit. 

## Usage and Impact

It is an important part of noisemodel to add to quantum circuit for noise simulation and error mitigation.

## Implementation

https://github.com/tencent-quantum-lab/tensorcircuit/blob/fc31d3b87278aff005b625d12a718c3bcb89fba4/tensorcircuit/channels.py

**Comment by refraction-ray** [comment]
finished
