### ISSUE TITLE
Add circuit block to generate quantum supremacy random circuit

### ISSUE THREAD

**Issue by refraction-ray** [tencent-quantum-lab/tensorcircuit#36]
## Task description

Add ``tc.templates.blocks.random_circuit`` to generate random circuit for demonstrating quantum supremacy, the circuit structure can be found from Google's paper: https://www.nature.com/articles/s41586-019-1666-5

## Implementation

Add a function ``random_circuit`` in ``/tensorcircuit/templates/blocks.py`` which generate the corresponding circuit with given spec (1D/2D, entangling gate type, depth, qubit number, etc.)

## Requirements

Difficulty: ★★

**Comment by SexyCarrots** [comment]
Is this the task for Tencent Spark Project?

**Comment by refraction-ray** [comment]
> Is this the task for Tencent Spark Project?

It can be if the students are too smart and the problems set is not enough for them. But in general, everyone from open source community is welcome to contribute to these tasks. These tasks are just features we'd like to see in future tensorcircuit.

**Comment by SexyCarrots** [comment]
Great. You are really building the community.

**Comment by refraction-ray** [comment]
currently we have an alternative that using `tc.Circuit.from_qsim()` to load google random circuit structure
