### ISSUE TITLE
How to get accurate expectation value of a circuit with conditional gates

### ISSUE THREAD

**Issue by royess** [tencent-quantum-lab/tensorcircuit#52]
I found that `conditional_gate` now is designed to work in a probabilistic way. I think a batched evaluation can work. But I want to know if there is a way to get the accurate expectation value, which is averaged over conditional measurement outcomes.

An example:
```python
c = tc.Circuit(nqubits)
c.h(0)
z = c.cond_measure(0)
c.conditional_gate(z, [tc.gates.i(), tc.gates.x()], 2)
print(c.expectation_ps(z=[2]))
```

Now it gives -1 and +1 each with a 0.5 possibilities. But I want to get 0 as an expectation instead. And I suppose in principle this is implementable in the tensor contraction manner.

And this is also related to #46 , where the expectation value of circuits with conditional gates is needed.

**Comment by refraction-ray** [comment]
I wonder whether the thing you really want is like a multi control gate:

```python
c = tc.Circuit(3)
c.h(0)
c.multicontrol(0, 2, unitary=tc.gates.x(), ctrl=[1])
c.expectation_ps(z=[2])
```

**Comment by royess** [comment]
Thanks for your reply! I think you are right that `multicontrol` is the correct choice for my example codes. And I realize that this works for QCNN as well.

> Or somehow, `multicontrol` and `cond_measure` are the same thing based on the philosophy of deferred measurement

That makes sense in the cases above and in most cases I can think about.
