### ISSUE TITLE
SPSA optimization example

### ISSUE THREAD

**Issue by refraction-ray** [tencent-quantum-lab/tensorcircuit#73]
## Task description

Example demonstrating VQE optimization using SPSA via https://github.com/andim/noisyopt package

## Implementation

add an scripts in `examples` or an jupyter notebook in `doc/source/tutorials`, actually slight change on https://github.com/tencent-quantum-lab/tensorcircuit/blob/master/examples/vqe_shot_noise.py

recommend to also include benchmark on the optimization performance comparison with other optimizers 

## Requirements

Difficulty: ★★

**Comment by Gopal-Dahale** [comment]
@refraction-ray #215.
