### ISSUE TITLE
Unexpected warning when calculating expectation with readout error

### ISSUE THREAD

**Issue by liwt31** [tencent-quantum-lab/tensorcircuit#89]
## Issue Description

Unexpected warning when calculating expectation with readout error.
The problem is at
https://github.com/tencent-quantum-lab/tensorcircuit/blob/b413089bd514c90b7998b9d2ca9125d5debd9849/tensorcircuit/noisemodel.py#L282

When counting gates, ``standardize_gate`` is called.

## How to Reproduce

```python
c = DMCircuit(2)

nc = NoiseConf()
re = 0.95
nc.add_noise("readout", [[re, re],[re, re]])
c.sample_expectation_ps([0], shots=1024, noise_conf=nc)
```

### Error Output

```python
WARNING:tensorcircuit.abstractcircuit:gate name not in the common gate set that tc supported
```

## Environment Context

commit df6679561e71cbc3eec1d3f5f2c731b008591a8f

**Comment by refraction-ray** [comment]
confirmed, to be fixed
