### ISSUE TITLE
Error on sigmoid and relu functions under pytorchbackend

### ISSUE THREAD

**Issue by NumnumnumM** [tencent-quantum-lab/tensorcircuit#97]
## Issue Description
The sigmoid and relu functions under pytorchbackend should use torch.sigmoid() and torch.relu() instead of torch.nn.Sigmoid() and torch.nn.Relu()

## How to Reproduce

```python
from tensorcircuit.backends.pytorch_backend import PyTorchBackend
a = torch.tensor(2)
model = PyTorchBackend()
out = model.sigmoid(a=a)
```

### Error Output

```python
TypeError                                 Traceback (most recent call last)
Cell In[2], line 4
      2 a = torch.tensor(2)
      3 model = PyTorchBackend()
----> 4 out = model.sigmoid(a=a)
      5 out

File /opt/conda/envs/work/lib/python3.10/site-packages/tensorcircuit/backends/pytorch_backend.py:354, in PyTorchBackend.sigmoid(self, a)
    353 def sigmoid(self, a: Tensor) -> Tensor:
--> 354     return torchlib.nn.Sigmoid(a)

TypeError: Module.__init__() takes 1 positional argument but 2 were given
```

## Environment Context
python=3.10.8
tensorcircuit=0.6.0
torch=1.13.1_cuda11.6

**Comment by refraction-ray** [comment]
thanks for the report! sigmoid has already been fixed in the latest commit before and will fix relu as well, should release a new version of tc in the following days

**Comment by NumnumnumM** [comment]
Will be fixed in the next version of tc
